/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Control;

import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Dolar
 */
public class Principal_Hospital extends javax.swing.JFrame {

    
    String nom;
    
    /**
     * Creates new form Principal_Hospital
     */
    public Principal_Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1174, Short.MAX_VALUE)
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alta De Medicos");

        jMenuItem2.setText("Especialidad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Medicos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Alta De Pacientes");

        jMenuItem4.setText("Pacientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Citas Medicas");

        jMenuItem5.setText("Citas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Reporte");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//ESPECIALIDAD
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        interfaz_especialidad especiali =new interfaz_especialidad();
     
        
        
          if(verificainternalabierta(especiali)){
                
                
                
            especiali.setVisible(true);
            pantalla.add(especiali);
           try {  
            especiali.setMaximum(rootPaneCheckingEnabled);
            
            
            
        } catch (PropertyVetoException ex) {
                
                
            Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }else{
                
                especiali.dispose();
                
                }
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//MEDICOS
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            
            interfaz_medicos medic =new interfaz_medicos();
            
            

            if(verificainternalabierta(medic)){
                
                
                
                medic.setVisible(true);
                pantalla.add(medic);
                try {
                    medic.setMaximum(rootPaneCheckingEnabled);
                    
                    
                    
                } catch (PropertyVetoException ex) {
                    
                    
                    Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                
                medic.dispose();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed
//PACIENTES
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
     interfaz_pacientes paci =new interfaz_pacientes();   
        
        
        
          if(verificainternalabierta(paci)){
                
                
          
            paci.setVisible(true);
            pantalla.add(paci);
           try {  
            paci.setMaximum(rootPaneCheckingEnabled);
            
            
            
        } catch (PropertyVetoException ex) {
                
                
            Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }else{
                
                paci.dispose();
                
                }
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
//CITAS
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // TODO add your handling code here:
            
            
            interfaz_citas cita =new interfaz_citas();
            

            
            if(verificainternalabierta(cita)){
                
                
                
                cita.setVisible(true);
                pantalla.add(cita);
                try {
                    cita.setMaximum(rootPaneCheckingEnabled);
                    
                    
                    
                } catch (PropertyVetoException ex) {
                    
                    
                    Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                
                cita.dispose();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
//REPORTES
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            // TODO add your handling code here:
            
            interfaz_reporte report =new interfaz_reporte();
            
            
            if(verificainternalabierta(report)){
                
                
                
                report.setVisible(true);
                pantalla.add(report);
                try {
                    report.setMaximum(rootPaneCheckingEnabled);
                    
                    
                    
                } catch (PropertyVetoException ex) {
                    
                    
                    Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                
                report.dispose();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal_Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    
    
    
       private boolean verificainternalabierta(Object obj){
    
JInternalFrame[] activos =this.pantalla.getAllFrames();


boolean cerrado = true;


int i=0;

while (i<activos.length && cerrado){
    
    
nom=obj.getClass().getSimpleName();


if(activos[i].getClass().getSimpleName().equalsIgnoreCase(nom))
    
cerrado=false;

i++;

}

return cerrado;
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal_Hospital VENTANA_PRINCIPAL =new Principal_Hospital();
                VENTANA_PRINCIPAL.setLocationRelativeTo(null);
                VENTANA_PRINCIPAL.setName("Ventana Principal");
                VENTANA_PRINCIPAL.setVisible(true);
                
                
                
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JDesktopPane pantalla;
    // End of variables declaration//GEN-END:variables
}
